[package]
name = "cfg-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dependency = { path = "../dependency" }

[features]
dependency_feature = ["dependency/dependency_feature"]
